[package]
name = "p2p-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
net2 = "0.2.38"
signal-hook = "0.3.15"
signal-hook-async-std = "0.2.2"
simple-dns = "0.5.2"
